services:
  - type: web
    name: resume-backend
    env: python

    buildCommand: |
      apt-get update && apt-get install -y mupdf mupdf-tools
      pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: OPENAI_API_KEY
        sync: false
